# constants.py
NUM_NODES = 300
NUM_FAMILIES = 60
FAMILY_SIZE = NUM_NODES // NUM_FAMILIES
INFECTION_RADIUS = 10
INFECTION_PROBABILITY = 0.15
CROSS_FAMILY_PROBABILITY = 0.05
SOCIAL_INTERACTION_PROBABILITY = 0.03
VIEW_LIMIT = 100
TIME_STEP = 0.3
RECOVERY_HOURS = 23
HOURS_PER_FRAME = 0.4
FRAMES_PER_HOUR = int(1 / HOURS_PER_FRAME)
RECOVERY_FRAMES = int(RECOVERY_HOURS * FRAMES_PER_HOUR)
DETECTION_DELAY_DAYS = [6, 4, 5]
DAYS_PER_FRAME = 0.15
FRAMES_PER_DAY = int(1 / DAYS_PER_FRAME)

